name: "Setup Arduino CLI"
description: "Download Arduino CLI and add it to the PATH"
author: "Arduino"
inputs:
  version:
    description: "Version to use. Example: 0.5.0"
    default: "0.x"
  token:
    description: "Personal access token (PAT) used to call the Github API."
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "green"
